services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --advertise-kafka-addr
      - redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  rustsf:
    security_opt:
      - "no-new-privileges:true"
    image: rustfs/rustfs:latest
    container_name: rustsf
    volumes:
      - ~/data:/dat
      - ~/logs:/logs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTSF_LOG_LEVEL=info
      - RUSTFS_OBS_ENDPOINT=http://otel-collector:4317
    networks:
      - rustsf-net

  kafka-producer:
    build: ./producer
    container_name: kafka-producer
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKER: redpanda:9092
      TOPIC: r023hf
      MIN_VALUE: 10
      MAX_VALUE: 50
      EVENTS_PER_SEC: 2

  rust-consumer:
    build:
      context: ./rust-consumer
      dockerfile: Dockerfile
    container_name: rust-consumer
    depends_on:
      - rustsf
    environment:
      RUSTFS_PATH: /mnt/data
      RUSTFS_API: http://rustsf:9000
    volumes:
      - ~/data:/mnt/data
    networks:
      - rustsf-net

networks:
  rustsf-net:
    driver: bridge